---
# tasks file for jenkins
- name: import apt key
  apt_key: 
    url: https://pkg.jenkins.io/debian-stable/jenkins-ci.org.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/jenkins.gpg

- name: import apt key
  apt_key: 
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/jenkins.gpg

- name: download apt repository file of jenkins
  apt_repository:
    repo: deb http://pkg.jenkins-ci.org/debian-stable binary/
    state: present
    filename: 'jenkins'
    update_cache: no

- name: install open-jdk
  apt: 
    update_cache: yes
    name: default-jdk
    state: latest

- name: install jenkins
  apt: 
    update_cache: yes
    name: jenkins
    state: latest

- name: replace configurtion
  template: src=jenkins.aptly dest=/etc/default/jenkins

- name: copy job
  copy: 
    src: "{{ role_path }}/files/aptly-jobs/"
    dest: /var/lib/jenkins/jobs
    owner: aptly
    group: jenkins
    remote_src: yes
    mode: '0755'
    directory_mode: yes

- name: change file permission
  file:
    path: /var/lib/jenkins
    owner: aptly
    group: jenkins
    mode: 0755
    state: directory

- name: change file permission
  file:
    path: /var/log/jenkins
    owner: aptly
    group: jenkins
    mode: 0755
    state: directory

- name: change file permission
  file:
    path: /var/cache/jenkins
    owner: aptly
    group: jenkins
    mode: 0755
    state: directory

- name: start jenkins
  service: name=jenkins state=started enabled=yes
