version: '3.2'
services:
  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch-cont
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=0.0.0.0
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
        #      volumes:
        #      - type : "bind"
        #        source : "${PWD}/data01"
        #        target : "/usr/share/elasticsearch/data"
    networks:
      - elastic
  kibana:
    image: kibana:7.14.1
    container_name: kibana-cont
    ports:
      - "5601:5601"
    environment:
      - SERVER_NAME="kibana.test.org"
      - ELASTICSEARCH_HOSTS=["http://192.168.8.93:9200"]
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
